<?php

class IqquestionsTableSeeder extends Seeder {
    public function run()
    {
    	// Jobcategory::truncate();

    	Iqquestion::create(['quesno' => 1, 'questions' => 'What is the roman numeral of 500?', 'option_A' => 'X', 'option_B' => 'L', 'option_C' => 'D', 'option_D' => 'M', 'answer' => 'D', 'difficulty' => 'easy']);
    	Iqquestion::create(['quesno' => 2, 'questions' => 'What does the "e" in "e-mail" stands for?', 'option_A' => 'electronic', 'option_B' => 'express', 'option_C' => 'edited', 'option_D' => 'electric', 'answer' => 'electronic', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 3, 'questions' => 'If you rearrange the letters "CIFAIPC" you would have the name of a(n):', 'option_A' => 'city', 'option_B' => 'animal', 'option_C' => 'ocean', 'option_D' => 'river', 'answer' => 'ocean', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 4, 'questions' => 'How many feet are there in one yard?', 'option_A' => '3', 'option_B' => '4', 'option_C' => '5', 'option_D' => '6', 'answer' => '3', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 5, 'questions' => 'John needs 13 bottles of water from the store. John can only carry 3 at a time. What is the minimum number of trips John needs to make to the store?', 'option_A' => '5', 'option_B' => '4', 'option_C' => '4 1/2', 'option_D' => '3', 'answer' => '5', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 6, 'questions' => 'What sign in the zodiac is characterized by a crab?', 'option_A' => 'Aquarius', 'option_B' => 'Cancer', 'option_C' => 'Taurus', 'option_D' => 'Aries', 'answer' => 'Cancer', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 7, 'questions' => 'Which one of the four is least like the other three?', 'option_A' => 'Dog', 'option_B' => 'Mouse', 'option_C' => 'Snake', 'option_D' => 'Cat', 'answer' => 'Snake', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 8, 'questions' => 'If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely Lazzies?', 'option_A' => 'True', 'option_B' => 'False', 'option_C' => 'Not so sure', 'option_D' => 'I dont know', 'answer' => 'True', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 9, 'questions' => 'Book is to Reading as Fork is to:', 'option_A' => 'Drawing', 'option_B' => 'Eating', 'option_C' => 'Stirring', 'option_D' => 'Writing', 'answer' => 'Eating', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 10, 'questions' => '8:4 as 10:', 'option_A' => '3', 'option_B' => '7', 'option_C' => '24', 'option_D' => '5', 'answer' => '5', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 11, 'questions' => 'The words "inclusive" and "exclusive" have:', 'option_A' => 'the same meaning', 'option_B' => 'different meaning', 'option_C' => 'are the opposite in meaning', 'option_D' => 'none of the above', 'answer' => 'are the opposite in meaning', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 12, 'questions' => '“Pig is to pork” as “Cow is to _____”', 'option_A' => 'Lamb', 'option_B' => 'Beef', 'option_C' => 'Stew', 'option_D' => 'Cattle', 'answer' => 'Beef', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 13, 'questions' => 'Which number should come next in the series: 1,3,6,10,15,', 'option_A' => '8', 'option_B' => '11', 'option_C' => '24', 'option_D' => '21', 'answer' => '21', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 14, 'questions' => 'Which number should come next in this series: 25,24,22,19,', 'option_A' => '10', 'option_B' => '8', 'option_C' => '15', 'option_D' => '13', 'answer' => '15', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 15, 'questions' => 'The word PARTICULAR is the opposite of:', 'option_A' => 'distinct', 'option_B' => 'vague', 'option_C' => 'exacting', 'option_D' => 'fussy', 'answer' => 'vague', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 16, 'questions' => 'Choose the number that is 1/4 of 1/2 of 1/5 of 200:', 'option_A' => '2', 'option_B' => '3', 'option_C' => '4', 'option_D' => '5', 'answer' => '5', 'difficulty' => 'easy']);
        Iqquestion::create(['quesno' => 17, 'questions' => 'Group A:{talkative,job,ecstatic} Group B:{angry,wind,loquacious} Find two words, one from each group, that are closest in meaning:', 'option_A' => 'talkative and wind', 'option_B' => 'job and angry', 'option_C' => 'talkative and loquacious', 'option_D' => 'ecstatic and angry', 'answer' => 'talkative and loquacious', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 18, 'questions' => 'Mary who is sixteen years old, is four times as old as her brother. How old will Mary be when she is twice as old as her brother?', 'option_A' => '20', 'option_B' => '24', 'option_C' => '26', 'option_D' => '28', 'answer' => '24', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 19, 'questions' => '1,1,2,3,4,5,8,13,21 - Which one does not belong to this series?', 'option_A' => '2', 'option_B' => '3', 'option_C' => '4', 'option_D' => '5', 'answer' => '4', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 20, 'questions' => 'Cat is to Dog as Peach is to?', 'option_A' => 'Juice', 'option_B' => 'Banana', 'option_C' => 'House', 'option_D' => 'Bear', 'answer' => 'Banana', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 21, 'questions' => 'I am a male. If Albert\'s son is my son\'s father, what is the relationship between Albert and me?', 'option_A' => 'he is my brother', 'option_B' => 'he is my uncle', 'option_C' => 'he is my father', 'option_D' => 'not related to me', 'answer' => 'he is my father', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 22, 'questions' => 'At the end of a banquet 10 people shake hands with each other. How many handshakes will there be in total?', 'option_A' => '45', 'option_B' => '100', 'option_C' => '90', 'option_D' => '50', 'answer' => '45', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 23, 'questions' => 'The mirror image of a clock at 2:45 will show the following time:', 'option_A' => '9:15', 'option_B' => '10:15', 'option_C' => '9:45', 'option_D' => '10:45', 'answer' => '9:15', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 24, 'questions' => ' 165135 is to peace as 1215225 is to', 'option_A' => 'lead', 'option_B' => 'love', 'option_C' => 'loop', 'option_D' => 'castle', 'answer' => 'love', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 25, 'questions' => 'What is the minimum number of toothpicks necessary to spell the word "HAT".  (You are not allowed to break or bend any toothpicks.)', 'option_A' => '8', 'option_B' => '7', 'option_C' => '6', 'option_D' => '5', 'answer' => '8', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 26, 'questions' => '657 - PUT, 758 - TUB, What is PUB?', 'option_A' => '557', 'option_B' => '658', 'option_C' => '857', 'option_D' => '678', 'answer' => '658', 'difficulty' => 'medium']);        
        Iqquestion::create(['quesno' => 27, 'questions' => 'How many meters will I be away from my home if I travel 5 meters towards North, take a right and travel 4 meters and travel 5 meters towards South?', 'option_A' => '5', 'option_B' => '4', 'option_C' => '10', 'option_D' => '14', 'answer' => '4', 'difficulty' => 'medium']);        
        Iqquestion::create(['quesno' => 28, 'questions' => 'There are 4 boys. Tom is shorter than John. Dave is taller than Tom but shorter than John. James is shorter than John but taller than Dave. Who is the shortest?', 'option_A' => 'John', 'option_B' => 'Dave', 'option_C' => 'James', 'option_D' => 'Tom', 'answer' => 'Tom', 'difficulty' => 'medium']);
        Iqquestion::create(['quesno' => 29, 'questions' => 'When unscrambled, what do the letters in this word spell out:  PLEAP', 'option_A' => 'A type of fruit', 'option_B' => 'A type of animal', 'option_C' => 'A type of clothing', 'option_D' => 'A type of building', 'answer' => 'A type of fruit', 'difficulty' => 'medium']);                
        Iqquestion::create(['quesno' => 30, 'questions' => 'Ralph likes 25 but not 24; he likes 400 but not 300; he likes 144 but not 145. Which does he like:', 'option_A' => '50', 'option_B' => '124', 'option_C' => '200', 'option_D' => '1600', 'answer' => '1600', 'difficulty' => 'medium']);        
    }
}
